# Generated by Django 3.2 on 2021-05-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20210511_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
