# Generated by Django 3.2 on 2021-05-13 08:08

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_signup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(default=None, max_length=50, verbose_name=django.contrib.auth.models.User),
        ),
    ]
