# Generated by Django 3.2 on 2021-05-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20210513_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='img',
            field=models.ImageField(blank=True, default='static/dashboard/profile.png', upload_to='pics'),
        ),
    ]
