# Generated by Django 3.2 on 2021-05-15 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0014_addstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('class_num', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=50)),
                ('stream_name', models.CharField(max_length=50)),
                ('no_of_subj', models.CharField(max_length=50)),
                ('name_of_subj', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
