# Generated by Django 3.2 on 2021-05-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='period6',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
