# Generated by Django 3.2 on 2021-05-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_timetable_period6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudent',
            old_name='_class',
            new_name='cla_ss',
        ),
    ]
